spring:
  application:
    name: aec-file

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1000MB}
      max-request-size: ${MAX_REQUEST_SIZE:1000MB}

server:
  port: ${PORT:8084}

jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://production-31f3.up.railway.app/api/files/oauth2/callback

gdrive:
  folder-product-id: 1oq7OFOCkuHWgzIXNRElQT1E9-5Jtx9f2
  folder-receipt-id: 1YZaBMd6OexyjuOpLf8IfeOJF9fzzw-Be

logging:
  level:
    org.springframework.security: ${LOG_SECURITY_LEVEL:DEBUG}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${LOG_FILTER_LEVEL:DEBUG}
    root: ${LOG_ROOT_LEVEL:INFO}