spring:
  application:
    name: aec-file

  # PostgreSQL datasource
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1000MB}
      max-request-size: ${MAX_REQUEST_SIZE:1000MB}

server:
  port: ${SERVER_PORT:8080}

# Ruta de subida de archivos (se puede montar en Railway como volumen si es necesario)
file:
  upload-dir: ${UPLOAD_DIR:uploads}

# Seguridad (si aplica JWT en este microservicio también)
jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

logging:
  level:
    org.springframework.security: ${LOG_SECURITY_LEVEL:DEBUG}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${LOG_FILTER_LEVEL:DEBUG}
    root: ${LOG_ROOT_LEVEL:INFO}
