spring:
  application:
    name: aec-file

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1000MB}
      max-request-size: ${MAX_REQUEST_SIZE:1000MB}

server:
  port: ${PORT:8084}

jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:36000000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

gdrive:
  folder-product-id: ${GDRIVE_FOLDER_PRODUCT_ID}
  folder-receipt-id: ${GDRIVE_FOLDER_RECEIPT_ID}
  refresh-token: ${GOOGLE_REFRESH_TOKEN:}   

logging:
  level:
    org.springframework.security: ${LOG_SECURITY_LEVEL:DEBUG}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${LOG_FILTER_LEVEL:DEBUG}
    root: ${LOG_ROOT_LEVEL:INFO}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,metrics,gateway,mappings,env,beans
  endpoint:
    health:
      show-details: always
